#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\* -y
sudo echo "frontend web
bind *:80
mode http
default_backend web

backend web
balance roundrobin
mode http
server 325400-web-01 52.23.178.146:80 check
server 325400-web-02 100.26.223.57:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
