#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file in the format:
# username:UID:home_directory

while IFS=":" read -r username _ uid _ _ home_directory _; do
    echo "$username:$uid:$home_directory"
done < /etc/passwd
