#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file as a story

while IFS=":" read -r username password uid gid gecos home_directory shell; do
    echo "The user $username is part of the $gid gang, lives in $home_directory and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
