#!/usr/bin/env bash
# This script displays the content of an apache log file in the format:
# OCCURRENCE_NUMBER IP HTTP_CODE

awk '{ print $1 " " $9 }' < apache-access.log | sort | uniq -c | sort -rn
